# Generated by Django 3.2.5 on 2021-07-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcozinha', '0002_auto_20210714_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='informacoes_basicas',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='ingrediente',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='modo_de_preparo',
            field=models.TextField(max_length=2000),
        ),
    ]
